import Head from "next/head";
import Hero from "../sections/Hero.jsx";
import Process from "../sections/Process.jsx";
import Projects from "../sections/Projects.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Process />
      <Projects />
    </>
  );
}
